#!/usr/bin/env php
<?php
define('INSTALL_DEPENDENCIES_HOME', getenv('INSTALL_DEPENDENCIES_HOME') ?: get_default_home());
define('DEPFILE', 'dependencies.json');
define('VERBOSE', true);

set_error_handler('exception_error_handler');
set_exception_handler('exit_exception_handler');

install_dependencies('.');


function install_dependencies($basedir)
{
    foreach (read_dependeciesfile($basedir . DIRECTORY_SEPARATOR . DEPFILE) as $dest => $url) {
        install_dependency($url, $basedir . DIRECTORY_SEPARATOR . $dest);
    }
}


function install_dependency($url, $dest)
{
    $cachedir = INSTALL_DEPENDENCIES_HOME . DIRECTORY_SEPARATOR . hash_url($url);
    if (!file_exists($cachedir)) {
        unlink(unzip(download($url), $cachedir));
        install_dependencies(skip_initial_directory($cachedir));
    }
    $releasedir = skip_initial_directory($cachedir);
    $subpath = parse_url($url, PHP_URL_FRAGMENT);
    install_link($releasedir . DIRECTORY_SEPARATOR . $subpath, $dest);
}


function download($url)
{
    info("downloading $url");
    $ch = curl_init($url);
    $filename = tempnam(sys_get_temp_dir(), 'dep');
    $fp = fopen($filename, 'w');
    curl_setopt($ch, CURLOPT_FILE, $fp);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_exec($ch);
    curl_close($ch);
    fclose($fp);
    assert(filesize($filename), 'download');
    return $filename;
}


function unzip($filename, $destination)
{
    info("extracting $filename to $destination");
    mkdir($destination, 0755, true);
    try {
        $zip = new ZipArchive();
        $zip->open($filename);
        $zip->extractTo($destination);
        $zip->close();
    } catch (Exception $e) {
        rmdir($destination);
        throw $e;
    }
    return $filename;
}


function install_link($target, $dest)
{
    info("linking $target to $dest");
    assert(file_exists($target), "install_link $target");
    if (file_exists($dest)) { // this needs to be worked out
        is_windows() ? rmdir($dest) : unlink($dest);
    }
    if (!file_exists(dirname($dest)))
        mkdir(dirname($dest), 0755, true);
    symlink($target, $dest);
}


function skip_initial_directory($directory)
{
    $files = glob($directory . DIRECTORY_SEPARATOR . '*');
    return (1 === count($files) && is_dir($files[0])) ? $files[0] : $directory;
}


function hash_url($url)
{
    return sha1(preg_replace('/#.+$/', '', $url));
}


function read_dependeciesfile($filename)
{
    $data = file_exists($filename) ? read_json($filename) : new stdClass();
    if (!is_object($data))
        throw new Exception(sprintf("Invalid json decoding of %s must be an object but got %s.", $filename, gettype($data)));
    return $data;
}


function read_json($filename)
{
    return json_decode(file_get_contents($filename));
}


function get_default_home()
{
    return get_user_home() . DIRECTORY_SEPARATOR . '.install-dependencies';
}


function get_user_home()
{
    return is_windows() ? $_SERVER['USERPROFILE'] : $_SERVER['HOME'];
}


function is_windows()
{
    return strtoupper(substr(PHP_OS, 0, 3)) === 'WIN';
}


function info($line)
{
    if (VERBOSE) {
        echo "$line\n";
    }
}


function exception_error_handler($errno, $errstr, $errfile, $errline )
{
    throw new ErrorException($errstr, $errno, 0, $errfile, $errline);
}


function exit_exception_handler($e)
{
    fwrite(STDERR, $e->getMessage() . ' on line ' . $e->getLine() . "\n");
    exit($e->getCode() ?: 1);
}
